version: '3.6'

networks:
  expose:
    external: true

services:
  server:
    image: charleslzq/frp
    networks:
      - expose
    ports:
      - "7000:7000"
      - "20000-20100:20000-20100"
    volumes:
      - /data/configs/frp/frps.ini:/etc/frp/frps.ini
      - /data/logs/frp:/var/log
    deploy:
      placement:
        constraints:
          - node.labels.loc == cloud
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 8M
      labels:
        - traefik.docker.network=expose
        - traefik.dashboard.port=7500
        - traefik.dashboard.frontend.rule=Host:frp.aws.zenq.me