version: '3.6'

networks:
  net:
    driver: overlay
    ipam:
      driver: default
      config:
        - subnet: 172.16.100.0/24

volumes:
  portainer_data:

services:
  portainer:
    image: portainer/portainer:latest
    command: -H unix:///var/run/docker.sock
    networks:
      - net
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.1'
          memory: 32M
        reservations:
          cpus: '0.1'
          memory: 8M
